#!/bin/sh

help()
{
    echo "Usage: $0 [-a SCRIPT_ACTION] [-d LINUX_DISTRO]"
    return 0
}

for f in $(find . -maxdepth 2 -name setup*.sh -type f)
do
    if test ! -x "$f"
    then
        echo "Setting script file $f as executable"
        chmod +x -v "$f"
    fi
done

test -z "$1" && help

while getopts 'a:d:h' arg
do
    case "${arg}" in
        a) SCRIPT_ACTION="$OPTARG";;
        d) LINUX_DISTRO="$OPTARG";;
        h) help;;
        *) help && exit 1;;
    esac
done

if test -z "${SCRIPT_ACTION}"
then
    echo "Nothing to do"
    exit 1
elif test -z "${LINUX_DISTRO}"
then
    echo "No distro was specified"
    exit 1
fi

case "${SCRIPT_ACTION}" in
    setup-secure-boot)  "${SHELL}" -c "LINUX_DISTRO=${LINUX_DISTRO} ./tools/setup.sh";;
    install-tkg-kernel) "${SHELL}" -c "LINUX_DISTRO=${LINUX_DISTRO} ./kernels/setup.sh";;
    setup-rootfs)       "${SHELL}" -c "LINUX_DISTRO=${LINUX_DISTRO} ./rootfs/setup.sh";;
    setup-services)     "${SHELL}" -c "LINUX_DISTRO=${LINUX_DISTRO} ./tools/setup-services.sh";;
    install-packages)   "${SHELL}" -c "LINUX_DISTRO=${LINUX_DISTRO} ./packages/setup.sh";;
    *)
        if test ! -z "${SCRIPT_ACTION}"
        then
            echo "error: $SCRIPT_ACTION: unknown action"
            exit 1
        fi
    ;;
esac

