#!/bin/sh

help()
{
    echo "Usage: $(basename $0) [OPTIONS]

Options:
    --setup-rootfs          Copy bootloader entries and other config files
    --install-packages      Install packages from a predefined list
    --help,-h               Show this message"

    return 1
}

check()
{
    if test "$(whoami)" = "root"
    then
        echo "Do not run this script as $(whoami)"
        return 1
    fi

    for f in packages rootfs
    do
        if test ! -d "$f"
        then
            echo "ERROR: Could not find the folder '$f'"
            return 1
        fi
    done

    return $?
}

install_packages()
{
    test -f "packages/setup.sh" && sh "packages/setup.sh" || return 1
    return $?
}

setup_rootfs()
{
    test -f "rootfs/setup.sh" && sh "rootfs/setup.sh" || return 1
    return $?
}

check

if test -z "$1"
then
    help
    exit 1
fi

if test $# -gt 1
then
    echo "Too many arguments" && help && exit 1
else
    while test $# -eq 1
    do
        case "$1" in
            --setup-rootfs) setup_rootfs; exit $?;;
            --install-packages) install_packages; exit $?;;
            --setup-all)
                install_packages || exit $?
                setup_rootfs || exit $?
            ;;
            --help|-h) help; exit $?;;
            *) printf ":: ERROR: unknown command: $1\n\n" && help && exit $?;;
        esac
        shift
    done
fi
