#!/bin/sh

command=$2

if [ "$command" = "started" ]
then
    systemctl set-property --runtime -- system.slice AllowedCPUs=0-3
    systemctl set-property --runtime -- user.slice AllowedCPUs=0-3
    systemctl set-property --runtime -- init.scope AllowedCPUs=0-3
elif [ "$command" = "release" ]
then
    systemctl set-property --runtime -- system.slice AllowedCPUs=0-7
    systemctl set-property --runtime -- user.slice AllowedCPUs=0-7
    systemctl set-property --runtime -- init.scope AllowedCPUs=0-7
fi
